version: '3.8'

services:
  mongo:
   image: mongo 
   restart: always
   ports:
     - 3456:27017
   command: [--auth]
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: example
     MONGO_INITDB_ROOT_DATABASE: the_database
   volumes:
     - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js